(cl:in-package mirobot-srv)
(cl:export '(RESULT-VAL
          RESULT
          STATE-VAL
          STATE
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          A-VAL
          A
          B-VAL
          B
          C-VAL
          C
          JOINTANGLE_1-VAL
          JOINTANGLE_1
          JOINTANGLE_2-VAL
          JOINTANGLE_2
          JOINTANGLE_3-VAL
          JOINTANGLE_3
          JOINTANGLE_4-VAL
          JOINTANGLE_4
          JOINTANGLE_5-VAL
          JOINTANGLE_5
          JOINTANGLE_6-VAL
          JOINTANGLE_6
          JOINTANGLE_7-VAL
          JOINTANGLE_7
))