// Generated by gencpp from file mirobot/GetPoseCmd.msg
// DO NOT EDIT!


#ifndef MIROBOT_MESSAGE_GETPOSECMD_H
#define MIROBOT_MESSAGE_GETPOSECMD_H

#include <ros/service_traits.h>


#include <mirobot/GetPoseCmdRequest.h>
#include <mirobot/GetPoseCmdResponse.h>


namespace mirobot
{

struct GetPoseCmd
{

typedef GetPoseCmdRequest Request;
typedef GetPoseCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPoseCmd
} // namespace mirobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirobot::GetPoseCmd > {
  static const char* value()
  {
    return "5aef3792e74d728815d4dfbf8b1f490f";
  }

  static const char* value(const ::mirobot::GetPoseCmd&) { return value(); }
};

template<>
struct DataType< ::mirobot::GetPoseCmd > {
  static const char* value()
  {
    return "mirobot/GetPoseCmd";
  }

  static const char* value(const ::mirobot::GetPoseCmd&) { return value(); }
};


// service_traits::MD5Sum< ::mirobot::GetPoseCmdRequest> should match
// service_traits::MD5Sum< ::mirobot::GetPoseCmd >
template<>
struct MD5Sum< ::mirobot::GetPoseCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirobot::GetPoseCmd >::value();
  }
  static const char* value(const ::mirobot::GetPoseCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirobot::GetPoseCmdRequest> should match
// service_traits::DataType< ::mirobot::GetPoseCmd >
template<>
struct DataType< ::mirobot::GetPoseCmdRequest>
{
  static const char* value()
  {
    return DataType< ::mirobot::GetPoseCmd >::value();
  }
  static const char* value(const ::mirobot::GetPoseCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirobot::GetPoseCmdResponse> should match
// service_traits::MD5Sum< ::mirobot::GetPoseCmd >
template<>
struct MD5Sum< ::mirobot::GetPoseCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirobot::GetPoseCmd >::value();
  }
  static const char* value(const ::mirobot::GetPoseCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirobot::GetPoseCmdResponse> should match
// service_traits::DataType< ::mirobot::GetPoseCmd >
template<>
struct DataType< ::mirobot::GetPoseCmdResponse>
{
  static const char* value()
  {
    return DataType< ::mirobot::GetPoseCmd >::value();
  }
  static const char* value(const ::mirobot::GetPoseCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIROBOT_MESSAGE_GETPOSECMD_H
