// Generated by gencpp from file mirobot/SetCartCmd.msg
// DO NOT EDIT!


#ifndef MIROBOT_MESSAGE_SETCARTCMD_H
#define MIROBOT_MESSAGE_SETCARTCMD_H

#include <ros/service_traits.h>


#include <mirobot/SetCartCmdRequest.h>
#include <mirobot/SetCartCmdResponse.h>


namespace mirobot
{

struct SetCartCmd
{

typedef SetCartCmdRequest Request;
typedef SetCartCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCartCmd
} // namespace mirobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirobot::SetCartCmd > {
  static const char* value()
  {
    return "a04e9b461fba38f9b9e9c58e02a554ec";
  }

  static const char* value(const ::mirobot::SetCartCmd&) { return value(); }
};

template<>
struct DataType< ::mirobot::SetCartCmd > {
  static const char* value()
  {
    return "mirobot/SetCartCmd";
  }

  static const char* value(const ::mirobot::SetCartCmd&) { return value(); }
};


// service_traits::MD5Sum< ::mirobot::SetCartCmdRequest> should match
// service_traits::MD5Sum< ::mirobot::SetCartCmd >
template<>
struct MD5Sum< ::mirobot::SetCartCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirobot::SetCartCmd >::value();
  }
  static const char* value(const ::mirobot::SetCartCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirobot::SetCartCmdRequest> should match
// service_traits::DataType< ::mirobot::SetCartCmd >
template<>
struct DataType< ::mirobot::SetCartCmdRequest>
{
  static const char* value()
  {
    return DataType< ::mirobot::SetCartCmd >::value();
  }
  static const char* value(const ::mirobot::SetCartCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirobot::SetCartCmdResponse> should match
// service_traits::MD5Sum< ::mirobot::SetCartCmd >
template<>
struct MD5Sum< ::mirobot::SetCartCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirobot::SetCartCmd >::value();
  }
  static const char* value(const ::mirobot::SetCartCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirobot::SetCartCmdResponse> should match
// service_traits::DataType< ::mirobot::SetCartCmd >
template<>
struct DataType< ::mirobot::SetCartCmdResponse>
{
  static const char* value()
  {
    return DataType< ::mirobot::SetCartCmd >::value();
  }
  static const char* value(const ::mirobot::SetCartCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIROBOT_MESSAGE_SETCARTCMD_H
