// Generated by gencpp from file mirobot/SetCartCmdRequest.msg
// DO NOT EDIT!


#ifndef MIROBOT_MESSAGE_SETCARTCMDREQUEST_H
#define MIROBOT_MESSAGE_SETCARTCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirobot
{
template <class ContainerAllocator>
struct SetCartCmdRequest_
{
  typedef SetCartCmdRequest_<ContainerAllocator> Type;

  SetCartCmdRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)
    , b(0.0)
    , c(0.0)
    , speed(0)  {
    }
  SetCartCmdRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)
    , b(0.0)
    , c(0.0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _a_type;
  _a_type a;

   typedef float _b_type;
  _b_type b;

   typedef float _c_type;
  _c_type c;

   typedef int32_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::mirobot::SetCartCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirobot::SetCartCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCartCmdRequest_

typedef ::mirobot::SetCartCmdRequest_<std::allocator<void> > SetCartCmdRequest;

typedef boost::shared_ptr< ::mirobot::SetCartCmdRequest > SetCartCmdRequestPtr;
typedef boost::shared_ptr< ::mirobot::SetCartCmdRequest const> SetCartCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirobot::SetCartCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirobot::SetCartCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirobot::SetCartCmdRequest_<ContainerAllocator1> & lhs, const ::mirobot::SetCartCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirobot::SetCartCmdRequest_<ContainerAllocator1> & lhs, const ::mirobot::SetCartCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirobot::SetCartCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirobot::SetCartCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirobot::SetCartCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirobot::SetCartCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirobot::SetCartCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirobot::SetCartCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirobot::SetCartCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cb59f49ecc10d65e626979481d18dd2";
  }

  static const char* value(const ::mirobot::SetCartCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cb59f49ecc10d65ULL;
  static const uint64_t static_value2 = 0xe626979481d18dd2ULL;
};

template<class ContainerAllocator>
struct DataType< ::mirobot::SetCartCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirobot/SetCartCmdRequest";
  }

  static const char* value(const ::mirobot::SetCartCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirobot::SetCartCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x \n"
"float32 y \n"
"float32 z \n"
"float32 a \n"
"float32 b \n"
"float32 c \n"
"int32 speed \n"
;
  }

  static const char* value(const ::mirobot::SetCartCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirobot::SetCartCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCartCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirobot::SetCartCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirobot::SetCartCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<float>::stream(s, indent + "  ", v.c);
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIROBOT_MESSAGE_SETCARTCMDREQUEST_H
