// Generated by gencpp from file mirobot/SetGcodeCmdRequest.msg
// DO NOT EDIT!


#ifndef MIROBOT_MESSAGE_SETGCODECMDREQUEST_H
#define MIROBOT_MESSAGE_SETGCODECMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirobot
{
template <class ContainerAllocator>
struct SetGcodeCmdRequest_
{
  typedef SetGcodeCmdRequest_<ContainerAllocator> Type;

  SetGcodeCmdRequest_()
    : gcode()  {
    }
  SetGcodeCmdRequest_(const ContainerAllocator& _alloc)
    : gcode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _gcode_type;
  _gcode_type gcode;





  typedef boost::shared_ptr< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetGcodeCmdRequest_

typedef ::mirobot::SetGcodeCmdRequest_<std::allocator<void> > SetGcodeCmdRequest;

typedef boost::shared_ptr< ::mirobot::SetGcodeCmdRequest > SetGcodeCmdRequestPtr;
typedef boost::shared_ptr< ::mirobot::SetGcodeCmdRequest const> SetGcodeCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirobot::SetGcodeCmdRequest_<ContainerAllocator1> & lhs, const ::mirobot::SetGcodeCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.gcode == rhs.gcode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirobot::SetGcodeCmdRequest_<ContainerAllocator1> & lhs, const ::mirobot::SetGcodeCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a46afe04400af260ebb86395c467524";
  }

  static const char* value(const ::mirobot::SetGcodeCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a46afe04400af26ULL;
  static const uint64_t static_value2 = 0x0ebb86395c467524ULL;
};

template<class ContainerAllocator>
struct DataType< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirobot/SetGcodeCmdRequest";
  }

  static const char* value(const ::mirobot::SetGcodeCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string gcode\n"
;
  }

  static const char* value(const ::mirobot::SetGcodeCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gcode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGcodeCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirobot::SetGcodeCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirobot::SetGcodeCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "gcode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.gcode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIROBOT_MESSAGE_SETGCODECMDREQUEST_H
