// Generated by gencpp from file mirobot/SetHomeCmd.msg
// DO NOT EDIT!


#ifndef MIROBOT_MESSAGE_SETHOMECMD_H
#define MIROBOT_MESSAGE_SETHOMECMD_H

#include <ros/service_traits.h>


#include <mirobot/SetHomeCmdRequest.h>
#include <mirobot/SetHomeCmdResponse.h>


namespace mirobot
{

struct SetHomeCmd
{

typedef SetHomeCmdRequest Request;
typedef SetHomeCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHomeCmd
} // namespace mirobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirobot::SetHomeCmd > {
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::mirobot::SetHomeCmd&) { return value(); }
};

template<>
struct DataType< ::mirobot::SetHomeCmd > {
  static const char* value()
  {
    return "mirobot/SetHomeCmd";
  }

  static const char* value(const ::mirobot::SetHomeCmd&) { return value(); }
};


// service_traits::MD5Sum< ::mirobot::SetHomeCmdRequest> should match
// service_traits::MD5Sum< ::mirobot::SetHomeCmd >
template<>
struct MD5Sum< ::mirobot::SetHomeCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirobot::SetHomeCmd >::value();
  }
  static const char* value(const ::mirobot::SetHomeCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirobot::SetHomeCmdRequest> should match
// service_traits::DataType< ::mirobot::SetHomeCmd >
template<>
struct DataType< ::mirobot::SetHomeCmdRequest>
{
  static const char* value()
  {
    return DataType< ::mirobot::SetHomeCmd >::value();
  }
  static const char* value(const ::mirobot::SetHomeCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirobot::SetHomeCmdResponse> should match
// service_traits::MD5Sum< ::mirobot::SetHomeCmd >
template<>
struct MD5Sum< ::mirobot::SetHomeCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirobot::SetHomeCmd >::value();
  }
  static const char* value(const ::mirobot::SetHomeCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirobot::SetHomeCmdResponse> should match
// service_traits::DataType< ::mirobot::SetHomeCmd >
template<>
struct DataType< ::mirobot::SetHomeCmdResponse>
{
  static const char* value()
  {
    return DataType< ::mirobot::SetHomeCmd >::value();
  }
  static const char* value(const ::mirobot::SetHomeCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIROBOT_MESSAGE_SETHOMECMD_H
