// Generated by gencpp from file mirobot/SetHomeCmdRequest.msg
// DO NOT EDIT!


#ifndef MIROBOT_MESSAGE_SETHOMECMDREQUEST_H
#define MIROBOT_MESSAGE_SETHOMECMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirobot
{
template <class ContainerAllocator>
struct SetHomeCmdRequest_
{
  typedef SetHomeCmdRequest_<ContainerAllocator> Type;

  SetHomeCmdRequest_()
    {
    }
  SetHomeCmdRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetHomeCmdRequest_

typedef ::mirobot::SetHomeCmdRequest_<std::allocator<void> > SetHomeCmdRequest;

typedef boost::shared_ptr< ::mirobot::SetHomeCmdRequest > SetHomeCmdRequestPtr;
typedef boost::shared_ptr< ::mirobot::SetHomeCmdRequest const> SetHomeCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirobot::SetHomeCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace mirobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::mirobot::SetHomeCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirobot/SetHomeCmdRequest";
  }

  static const char* value(const ::mirobot::SetHomeCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::mirobot::SetHomeCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetHomeCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirobot::SetHomeCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mirobot::SetHomeCmdRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MIROBOT_MESSAGE_SETHOMECMDREQUEST_H
