// Generated by gencpp from file mirobot/SetJointCmd.msg
// DO NOT EDIT!


#ifndef MIROBOT_MESSAGE_SETJOINTCMD_H
#define MIROBOT_MESSAGE_SETJOINTCMD_H

#include <ros/service_traits.h>


#include <mirobot/SetJointCmdRequest.h>
#include <mirobot/SetJointCmdResponse.h>


namespace mirobot
{

struct SetJointCmd
{

typedef SetJointCmdRequest Request;
typedef SetJointCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointCmd
} // namespace mirobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirobot::SetJointCmd > {
  static const char* value()
  {
    return "b5f68cbcaa5e7a8e8c34ee9959541272";
  }

  static const char* value(const ::mirobot::SetJointCmd&) { return value(); }
};

template<>
struct DataType< ::mirobot::SetJointCmd > {
  static const char* value()
  {
    return "mirobot/SetJointCmd";
  }

  static const char* value(const ::mirobot::SetJointCmd&) { return value(); }
};


// service_traits::MD5Sum< ::mirobot::SetJointCmdRequest> should match
// service_traits::MD5Sum< ::mirobot::SetJointCmd >
template<>
struct MD5Sum< ::mirobot::SetJointCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirobot::SetJointCmd >::value();
  }
  static const char* value(const ::mirobot::SetJointCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirobot::SetJointCmdRequest> should match
// service_traits::DataType< ::mirobot::SetJointCmd >
template<>
struct DataType< ::mirobot::SetJointCmdRequest>
{
  static const char* value()
  {
    return DataType< ::mirobot::SetJointCmd >::value();
  }
  static const char* value(const ::mirobot::SetJointCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirobot::SetJointCmdResponse> should match
// service_traits::MD5Sum< ::mirobot::SetJointCmd >
template<>
struct MD5Sum< ::mirobot::SetJointCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirobot::SetJointCmd >::value();
  }
  static const char* value(const ::mirobot::SetJointCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirobot::SetJointCmdResponse> should match
// service_traits::DataType< ::mirobot::SetJointCmd >
template<>
struct DataType< ::mirobot::SetJointCmdResponse>
{
  static const char* value()
  {
    return DataType< ::mirobot::SetJointCmd >::value();
  }
  static const char* value(const ::mirobot::SetJointCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIROBOT_MESSAGE_SETJOINTCMD_H
